"use client";

import { useEffect, useState } from "react";
import { TestTube, Calendar, AlertTriangle, CheckCircle, Loader2, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Recommendation {
  test: string;
  reason: string;
  frequency: string;
  priority: "high" | "medium" | "routine";
}

export default function RecommendationsClient() {
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  async function fetchRecommendations() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/recommendations");
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to load recommendations.");
      setRecommendations(data.recommendations);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Something went wrong.");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { fetchRecommendations(); }, []);

  const high = recommendations.filter((r) => r.priority === "high");
  const medium = recommendations.filter((r) => r.priority === "medium");
  const routine = recommendations.filter((r) => r.priority === "routine");

  return (
    <div className="mx-auto max-w-4xl space-y-8">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Recommendations</h1>
          <p className="text-muted-foreground">
            Personalised screenings based on your family history and medical guidelines.
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={fetchRecommendations} disabled={loading} className="gap-2 shrink-0">
          <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} />
          Refresh
        </Button>
      </div>

      {loading && (
        <div className="flex flex-col items-center justify-center gap-3 py-20 text-muted-foreground">
          <Loader2 className="h-8 w-8 animate-spin text-primary" />
          <p className="text-sm">Claude is reviewing your family history...</p>
        </div>
      )}

      {error && (
        <div className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">
          {error}
        </div>
      )}

      {!loading && !error && (
        <>
          {high.length > 0 && (
            <div>
              <div className="mb-3 flex items-center gap-2">
                <AlertTriangle className="h-4 w-4 text-red-500" />
                <h2 className="font-semibold text-red-600">High Priority</h2>
              </div>
              <div className="space-y-3">
                {high.map((rec) => (
                  <RecommendationCard key={rec.test} rec={rec} accentClass="border-red-100 bg-red-50/50" iconClass="text-red-500" />
                ))}
              </div>
            </div>
          )}

          {medium.length > 0 && (
            <div>
              <div className="mb-3 flex items-center gap-2">
                <TestTube className="h-4 w-4 text-orange-500" />
                <h2 className="font-semibold text-orange-600">Recommended</h2>
              </div>
              <div className="space-y-3">
                {medium.map((rec) => (
                  <RecommendationCard key={rec.test} rec={rec} accentClass="border-orange-100 bg-orange-50/50" iconClass="text-orange-500" />
                ))}
              </div>
            </div>
          )}

          {routine.length > 0 && (
            <div>
              <div className="mb-3 flex items-center gap-2">
                <CheckCircle className="h-4 w-4 text-green-600" />
                <h2 className="font-semibold text-green-700">Routine</h2>
              </div>
              <div className="space-y-3">
                {routine.map((rec) => (
                  <RecommendationCard key={rec.test} rec={rec} accentClass="" iconClass="text-green-600" />
                ))}
              </div>
            </div>
          )}

          <div className="rounded-xl border bg-muted/50 p-4 text-xs text-muted-foreground">
            <strong>Disclaimer:</strong> These recommendations are generated by AI based on your family history and general medical guidelines. They are not a substitute for professional medical advice. Always consult your healthcare provider.
          </div>
        </>
      )}
    </div>
  );
}

function RecommendationCard({ rec, accentClass, iconClass }: {
  rec: Recommendation;
  accentClass: string;
  iconClass: string;
}) {
  return (
    <div className={`flex items-start gap-4 rounded-xl border bg-card p-4 ${accentClass}`}>
      <TestTube className={`mt-0.5 h-5 w-5 shrink-0 ${iconClass}`} />
      <div className="flex-1">
        <h3 className="font-semibold">{rec.test}</h3>
        <p className="text-sm text-muted-foreground">{rec.reason}</p>
      </div>
      <div className="flex items-center gap-1 text-xs text-muted-foreground shrink-0">
        <Calendar className="h-3 w-3" />
        {rec.frequency}
      </div>
    </div>
  );
}
